### ISSUE TITLE
File Name Error causes Error 500 in admin panel

### ISSUE THREAD

**Issue by IvarioD** [smartlook/smartlook-plugin-magento#1]
In the Magento 1.9 version there is a file name error for the file Smartsupp/Smartlook/Model/Config/Source/Showhide.php

The file is named ShowHide.php while the fetched resource in Autoload is Showhide.php.
Fixed the issue by changing the file name.

**Comment by krsiakdaniel** [comment]
Hi @IvarioD and thanks for reporting this issue. We will look into this. Thanks for taking the time to let us know.

~ Daniel
Smartlook

**Comment by krsiakdaniel** [comment]
File renamed to: Showhide.php
